import type { Metadata } from "next";
import { Exo_2 } from 'next/font/google';
import { Provider } from "@/components/ui/provider";
import { Container } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const exo2 = Exo_2({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={exo2.className}>
        <Provider>
          <Container maxW="1200px" py={5}>
            {children}
          </Container>
        </Provider>
      </body>
    </html>
  );
}
