export const ENDPOINTS = {
    TYPE: 'type',
    POKEMON: 'pokemon',
    POKEMON_GENERATION: 'generation',
};

export const POKEMON_TYPE = {
    BUG: 'bug',
    DARK: 'dark',
    DRAGON: 'dragon',
    ELECTRIC: 'electric',
    FAIRY: 'fairy',
    FIGHTING: 'fighting',
    FIRE: 'fire',
    FLYING: 'flying',
    GHOST: 'ghost',
    GRASS: 'grass',
    GROUND: 'ground',
    ICE: 'ice',
    NORMAL: 'normal',
    POISON: 'poison',
    PSYCHIC: 'psychic',
    ROCK: 'rock',
    STEEL: 'steel',
    WATER: 'water',
}

export const POKEMON_TYPE_ICON = {
    [POKEMON_TYPE.BUG]: "/icons/bug.png",
    [POKEMON_TYPE.DARK]: "/icons/bugdark.png",
    [POKEMON_TYPE.DRAGON]: "/icons/dragon.png",
    [POKEMON_TYPE.ELECTRIC]: "/icons/electric.png",
    [POKEMON_TYPE.FAIRY]: "/icons/fairy.png",
    [POKEMON_TYPE.FIGHTING]: "/icons/fighting.png",
    [POKEMON_TYPE.FIRE]: "/icons/fire.png",
    [POKEMON_TYPE.FLYING]: "/icons/flying.png",
    [POKEMON_TYPE.GHOST]: "/icons/ghost.png",
    [POKEMON_TYPE.GRASS]: "/icons/grass.png",
    [POKEMON_TYPE.GROUND]: "/icons/ground.png",
    [POKEMON_TYPE.ICE]: "/icons/ice.png",
    [POKEMON_TYPE.NORMAL]: "/icons/normal.png",
    [POKEMON_TYPE.POISON]: "/icons/poison.png",
    [POKEMON_TYPE.PSYCHIC]: "/icons/psychic.png",
    [POKEMON_TYPE.ROCK]: "/icons/rock.png",
    [POKEMON_TYPE.STEEL]: "/icons/stell.png",
    [POKEMON_TYPE.WATER]: "/icons/water.png",
};

export const POKEMON_TYPE_LABEL = [
    { label: 'Bug', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.BUG] },
    { label: 'Dark', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.DARK] },
    { label: 'Dragon', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.DRAGON] },
    { label: 'Electric', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.ELECTRIC] },
    { label: 'Fairy', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.FAIRY] },
    { label: 'Fighting', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.FIGHTING] },
    { label: 'Fire', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.FIRE] },
    { label: 'Flying', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.FLYING] },
    { label: 'Ghost', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.GHOST] },
    { label: 'Grass', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.GRASS] },
    { label: 'Ground', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.GROUND] },
    { label: 'Ice', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.ICE] },
    { label: 'Normal', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.NORMAL] },
    { label: 'Poison', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.POISON] },
    { label: 'Psychic', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.PSYCHIC] },
    { label: 'Rock', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.ROCK] },
    { label: 'Steel', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.STEEL] },
    { label: 'Water', icon: POKEMON_TYPE_ICON[POKEMON_TYPE.WATER] },
];